version: "3.6"
services:
  django:
    build: .
    # environment:
    #   -
    depends_on:
      - postgres
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/app

  postgres:
    image: circleci/postgres:12.3-postgis
    volumes:
      - postgres123-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

volumes:
  postgres123-data: {}
