# Generated by Django 3.2 on 2021-12-09 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TypeOfCuisine",
            fields=[
                (
                    "type_of_cuisine_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Type of cuisine",
                "verbose_name_plural": "Types of cuisine",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("menu_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=2000)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "type_of_cuisine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="menu.typeofcuisine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
